spring.application.name: time-based-charger-samples
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/settlements
    username: choicore
    password: secret

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        generate_statistics: true
        show_sql: true
        format_sql: true
        highlight_sql: true