spring.application.name: time-based-charger-samples
spring:
  devtools:
    restart:
      enabled: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/settlements
    username: choicore
    password: secret

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: false
        show_sql: false
        format_sql: false
        highlight_sql: false
        discriminator:
          ignore_explicit_for_joined: true

  threads:
    virtual:
      enabled: true